import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="Scientific Abstract Simplifier",
    page_icon="🧪",
    layout="wide"
)

FILES = {
    "General Adult": "promptsearch_general_predictions.csv",
    "Middle School": "promptsearch_middle_school_predictions.csv",
    "Undergraduate": "promptsearch_undergraduate_predictions.csv",
}

st.title("🧪 Audience-Aware Scientific Abstract Simplification")
st.write("Explore outputs already generated by our NLP models.")

audience = st.selectbox("Choose audience", list(FILES.keys()))

df = pd.read_csv(FILES[audience])

example_number = st.slider(
    "Choose test example",
    min_value=1,
    max_value=len(df),
    value=1
)

row = df.iloc[example_number - 1]

st.caption(f"Journal: {row.get('journal', 'Not available')}")

left, right = st.columns(2)

with left:
    st.subheader("Original Scientific Abstract")
    st.write(row["source"])

with right:
    st.subheader(f"Simplified for {audience}")
    st.write(row["prediction"])

with st.expander("Human-written reference"):
    st.write(row["reference"])

st.subheader("Overall Experiment Results")

results = pd.read_csv("final_results_table.csv")
st.dataframe(results, use_container_width=True)
