# -*- coding: utf-8 -*-
"""NLP_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uhI2M1s2M8PpMfPzhXTun0oMK_DFTy8
"""

#!/bin/bash
# STEP 1: Run this first in Google Colab terminal or as a cell with !

!pip install datasets transformers accelerate peft bitsandbytes
!pip install evaluate rouge_score bert_score
!pip install textstat
!pip install dspy-ai
!pip install alignscore
!pip install sentencepiece
!pip install matplotlib seaborn pandas numpy
!pip install easse  # for SARI metric

#!/usr/bin/env python3
# STEP 2: Load SciLay + Run EDA
# No GPU needed — runs on free Colab CPU
# Dataset: disi-unibo-nlp/SciLay
# Keys: technical_text (abstract), plain_text (lay summary), journal

import pandas as pd
import numpy as np
import textstat
import json
from datasets import load_dataset

# ── Load Dataset ──────────────────────────────────────────────────────────────
print("Loading SciLay (all journals)...")
dataset = load_dataset("disi-unibo-nlp/SciLay", "all")
print(f"Train: {len(dataset['train'])} | Val: {len(dataset['validation'])} | Test: {len(dataset['test'])}")

# Confirm field names
sample = dataset['train'][0]
print("\nFields available:", list(sample.keys()))
print("\nSample technical_text (abstract, first 300 chars):")
print(sample['technical_text'][:300])
print("\nSample plain_text (lay summary, first 300 chars):")
print(sample['plain_text'][:300])
print("\nJournal:", sample['journal'])

# ── Journal → Domain Mapping ─────────────────────────────────────────────────
# SciLay subset codes and their domains
JOURNAL_DOMAIN = {
    'NC':    'biology',      # Nature Communications
    'A':     'biology',      # Animals (MDPI)
    'PLGEN': 'biology',      # PLoS Genetics
    'PLPAT': 'medicine',     # PLoS Pathogens
    'PLCB':  'cs',           # PLoS Computational Biology
    'PLNTD': 'medicine',     # PLoS Neglected Tropical Diseases
    'B':     'biology',      # Biology
    'I':     'biology',      # Insects
    'PLB':   'biology',      # PLoS Biology
    'CB':    'biology',      # Communications Biology
    'SD':    'cs',           # Scientific Data
    'MBIO':  'medicine',     # mBio
    'C':     'medicine',     # Cancers
    'OTHER': 'other',
}

def get_domain(journal_str):
    """Map journal name string to domain using keyword matching."""
    j = journal_str.lower()
    if any(x in j for x in ['cancer', 'pathogen', 'neglected', 'mbio', 'disease']):
        return 'medicine'
    elif any(x in j for x in ['computational', 'scientific data']):
        return 'cs'
    elif any(x in j for x in ['genetics', 'biology', 'nature', 'animal',
                                'insect', 'communications bio']):
        return 'biology'
    else:
        return 'other'

# ── Rare word proxy ───────────────────────────────────────────────────────────
def rare_word_ratio(text):
    words = text.lower().split()
    if not words:
        return 0.0
    return sum(1 for w in words if len(w) > 8) / len(words)

# ── Compute Stats ─────────────────────────────────────────────────────────────
print("\nComputing FKGL and statistics (2-3 minutes)...")

records = []
for split in ['train', 'validation', 'test']:
    for example in dataset[split]:
        abstract = example['technical_text']
        summary  = example['plain_text']
        journal  = example.get('journal', '')

        # Filter very short examples
        if not abstract or not summary:
            continue
        if len(summary.split()) < 30 or len(abstract.split()) < 30:
            continue

        src_fkgl   = textstat.flesch_kincaid_grade(abstract)
        ref_fkgl   = textstat.flesch_kincaid_grade(summary)
        src_tokens = len(abstract.split())
        ref_tokens = len(summary.split())
        src_rare   = rare_word_ratio(abstract)
        ref_rare   = rare_word_ratio(summary)
        domain     = get_domain(journal)

        records.append({
            'split':      split,
            'journal':    journal,
            'domain':     domain,
            'src_fkgl':   src_fkgl,
            'ref_fkgl':   ref_fkgl,
            'fkgl_delta': src_fkgl - ref_fkgl,
            'src_tokens': src_tokens,
            'ref_tokens': ref_tokens,
            'len_ratio':  ref_tokens / max(src_tokens, 1),
            'src_rare':   src_rare,
            'ref_rare':   ref_rare,
        })

df = pd.DataFrame(records)
print(f"Total valid examples: {len(df)}")

# ── Print Summary ─────────────────────────────────────────────────────────────
print("\n=== OVERALL STATS ===")
print(df[['src_fkgl','ref_fkgl','fkgl_delta',
          'src_tokens','ref_tokens','src_rare','ref_rare']].describe().round(2))

print("\n=== FKGL BY DOMAIN ===")
print(df.groupby('domain')[['src_fkgl','ref_fkgl','fkgl_delta']].mean().round(2))

print("\n=== TOKEN LENGTH BY DOMAIN ===")
print(df.groupby('domain')[['src_tokens','ref_tokens','len_ratio']].mean().round(2))

print("\n=== DOMAIN DISTRIBUTION ===")
print(df['domain'].value_counts())

print("\n=== TOP JOURNALS ===")
print(df['journal'].value_counts().head(10))

# ── Save ──────────────────────────────────────────────────────────────────────
df.to_csv('eda_results.csv', index=False)

stats = {
    'overall': {
        'mean_src_fkgl':   round(float(df['src_fkgl'].mean()), 2),
        'mean_ref_fkgl':   round(float(df['ref_fkgl'].mean()), 2),
        'mean_fkgl_delta': round(float(df['fkgl_delta'].mean()), 2),
        'mean_src_tokens': round(float(df['src_tokens'].mean()), 1),
        'mean_ref_tokens': round(float(df['ref_tokens'].mean()), 1),
        'mean_src_rare':   round(float(df['src_rare'].mean()), 3),
        'mean_ref_rare':   round(float(df['ref_rare'].mean()), 3),
    },
    'by_domain': df.groupby('domain')[['src_fkgl','ref_fkgl','fkgl_delta']].mean().round(2).to_dict()
}

with open('eda_summary.json', 'w') as f:
    json.dump(stats, f, indent=2)

print("\n=== COPY THESE INTO YOUR PAPER ===")
print(json.dumps(stats['overall'], indent=2))
print("\nSaved: eda_results.csv + eda_summary.json")

!wget https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt

# EASSE (for SARI) — install from GitHub, not pip
!pip install git+https://github.com/feralvam/easse.git

# AlignScore — install from GitHub + download checkpoint
!pip install git+https://github.com/yuh-zha/AlignScore.git
!python -m spacy download en_core_web_sm

!pip install -q evaluate rouge_score bert_score textstat sacrebleu sentencepiece

import json
import numpy as np
import textstat
import torch
from bert_score import score as bert_score_fn
from evaluate import load
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Metrics via HuggingFace evaluate
rouge_metric = load("rouge")
bleu_metric  = load("bleu")
sari_metric  = load("sari")

# Factual consistency via NLI entailment (replaces AlignScore, installs cleanly)
print("Loading NLI model for factual consistency...")
NLI_MODEL = "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
nli_tok   = AutoTokenizer.from_pretrained(NLI_MODEL)
nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL)
nli_model.eval()
if torch.cuda.is_available():
    nli_model = nli_model.cuda()
print("Ready.")


def factual_consistency(sources, predictions):
    """
    Returns mean entailment probability: does the source entail the prediction?
    High score = prediction is supported by source = factually consistent.
    """
    scores = []
    for src, pred in zip(sources, predictions):
        inputs = nli_tok(src, pred, truncation=True, max_length=512,
                         return_tensors="pt")
        if torch.cuda.is_available():
            inputs = {k: v.cuda() for k, v in inputs.items()}
        with torch.no_grad():
            logits = nli_model(**inputs).logits
        probs = torch.softmax(logits, dim=-1)[0]
        # label order: 0=entailment, 1=neutral, 2=contradiction
        scores.append(float(probs[0].item()))
    return float(np.mean(scores))


def evaluate_system(sources, predictions, references, system_name="model"):
    """
    sources:     original abstracts     (technical_text)
    predictions: model simplifications
    references:  human lay summaries    (plain_text)
    """
    print(f"\nEvaluating: {system_name} ({len(sources)} examples)")
    assert len(sources) == len(predictions) == len(references)

    # 1. SARI
    sari = sari_metric.compute(
        sources=sources,
        predictions=predictions,
        references=[[r] for r in references]
    )['sari']

    # 2. ROUGE-L
    rougeL = rouge_metric.compute(
        predictions=predictions,
        references=references,
        rouge_types=['rougeL']
    )['rougeL']

    # 3. BLEU-4
    bleu4 = bleu_metric.compute(
        predictions=predictions,
        references=[[r] for r in references]
    )['bleu']

    # 4. BERTScore F1
    _, _, F1 = bert_score_fn(predictions, references, lang='en', verbose=False)
    bertscore = float(F1.mean().item())

    # 5. FKGL reduction
    src_fkgl  = [textstat.flesch_kincaid_grade(s) for s in sources]
    pred_fkgl = [textstat.flesch_kincaid_grade(p) for p in predictions]
    fkgl_delta = float(np.mean([s - p for s, p in zip(src_fkgl, pred_fkgl)]))

    # 6. Factual consistency (NLI entailment)
    factscore = factual_consistency(sources, predictions)

    results = {
        'system':     system_name,
        'n':          len(sources),
        'SARI':       round(sari, 3),
        'ROUGE-L':    round(rougeL, 3),
        'BLEU-4':     round(bleu4, 3),
        'BERTScore':  round(bertscore, 3),
        'FKGL_delta': round(fkgl_delta, 2),
        'FactScore':  round(factscore, 3),
    }
    print(json.dumps(results, indent=2))
    return results


# ── Sanity Check ──
if __name__ == "__main__":
    sources = [
        "The mitochondrial permeability transition pore (mPTP) is a nonselective "
        "channel implicated in apoptotic and necrotic cell death pathways.",
        "Receptor tyrosine kinases (RTKs) are high-affinity cell surface receptors "
        "for many polypeptide growth factors, cytokines, and hormones.",
    ]
    predictions = [
        "Cells have tiny doors that can open and cause the cell to die.",
        "Some proteins on the surface of cells receive signals that help cells grow.",
    ]
    references = [
        "Special channels in cells can open and lead to cell death.",
        "Certain proteins on cells receive growth signals.",
    ]
    evaluate_system(sources, predictions, references, "sanity_check")
    print("\nSanity check passed!")

from huggingface_hub import login
login()

import os
os.environ['HF_TOKEN'] = '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'

!pip install -q transformers accelerate bitsandbytes datasets evaluate rouge_score bert_score textstat sacrebleu sentencepiece

import torch
import json
import numpy as np
import pandas as pd
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# reduce memory fragmentation on T4
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

print("Loading Llama 3 8B Instruct (4-bit)...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
)
model.eval()
print("Model loaded.")

AUDIENCE_PROMPTS = {
    "general": (
        "You are a science communicator. Rewrite the following scientific abstract "
        "in plain English for a general adult reader with no scientific background. "
        "Keep all the key findings but use simple, everyday language.\n\n"
        "Abstract:\n{abstract}\n\nSimplified version:"
    ),
    "middle_school": (
        "You are a science teacher. Rewrite the following scientific abstract "
        "so that a middle school student aged 12 to 14 can understand it. "
        "Use very simple words and short sentences. Explain any technical terms.\n\n"
        "Abstract:\n{abstract}\n\nSimplified version:"
    ),
    "undergraduate": (
        "You are a science writer. Rewrite the following scientific abstract "
        "for an undergraduate student with basic science knowledge but no "
        "specialization in this field. Keep technical accuracy but clarify "
        "any highly specialized terminology.\n\n"
        "Abstract:\n{abstract}\n\nSimplified version:"
    ),
}

def generate(abstract, audience="general", max_new_tokens=256):
    prompt   = AUDIENCE_PROMPTS[audience].format(abstract=abstract)
    messages = [{"role": "user", "content": prompt}]

    # tokenize returns a plain tensor (not a dict)
    input_ids = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=False,          # <-- force plain tensor
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    generated = output[0][input_ids.shape[-1]:]
    return tokenizer.decode(generated, skip_special_tokens=True).strip()

print("\nLoading SciLay...")
dataset = load_dataset("disi-unibo-nlp/SciLay", "all")

N = 50   # START SMALL — change to 200 once you confirm it works
test_data = dataset['test'].select(range(min(N, len(dataset['test']))))
sources    = [ex['technical_text'] for ex in test_data]
references = [ex['plain_text']     for ex in test_data]
journals   = [ex.get('journal', '') for ex in test_data]
print(f"Running on {len(sources)} test examples")

all_results = {}
for audience in ["general", "middle_school", "undergraduate"]:
    print(f"\n{'='*50}\nAudience: {audience}\n{'='*50}")
    predictions = []
    for i, abstract in enumerate(sources):
        if i % 10 == 0:
            print(f"  {i}/{len(sources)}")
        predictions.append(generate(abstract, audience=audience))

    pd.DataFrame({
        'source': sources, 'prediction': predictions,
        'reference': references, 'journal': journals,
    }).to_csv(f'llama3_zeroshot_{audience}_predictions.csv', index=False)

    results = evaluate_system(
        sources=sources, predictions=predictions,
        references=references, system_name=f"llama3_zeroshot_{audience}"
    )
    all_results[audience] = results

with open('llama3_zeroshot_results.json', 'w') as f:
    json.dump(all_results, f, indent=2)
print("\nDone! Saved llama3_zeroshot_results.json")

# Run this FIRST to save your baseline before fine-tuning
from google.colab import files
import shutil, os
os.makedirs('/content/results_backup', exist_ok=True)
for f in ['llama3_zeroshot_general_predictions.csv',
          'llama3_zeroshot_middle_school_predictions.csv',
          'llama3_zeroshot_undergraduate_predictions.csv',
          'llama3_zeroshot_results.json']:
    if os.path.exists(f):
        shutil.copy(f, '/content/results_backup/')
print("Backed up. Files:", os.listdir('/content/results_backup'))

import torch, gc
try:
    del model, tokenizer
except NameError:
    pass
gc.collect()
torch.cuda.empty_cache()
print(f"Free GPU: {torch.cuda.mem_get_info()[0]/1e9:.1f} GB")

import torch
import json
import numpy as np
import pandas as pd
from datasets import load_dataset
from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM,
    Seq2SeqTrainer, Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq, EarlyStoppingCallback
)

# ── Change to "bart" for the second run ──
MODEL_KEY = "t5"

CONFIGS = {
    "t5": {
        "model_name": "t5-base", "max_input": 512, "max_target": 200,
        "learning_rate": 3e-4, "batch_size": 8, "epochs": 3, "prefix": "summarize: ",
    },
    "bart": {
        "model_name": "facebook/bart-base",   # base not large — fits T4
        "max_input": 512, "max_target": 200,
        "learning_rate": 3e-5, "batch_size": 4, "epochs": 3, "prefix": "",
    },
}
cfg = CONFIGS[MODEL_KEY]
print(f"Training: {cfg['model_name']}")

# ── Load SciLay ──
dataset = load_dataset("disi-unibo-nlp/SciLay", "all")
print(f"Train: {len(dataset['train'])} | Val: {len(dataset['validation'])} | Test: {len(dataset['test'])}")

# OPTIONAL: subset training data to save time on T4 (comment out for full run)
dataset['train'] = dataset['train'].select(range(min(5000, len(dataset['train']))))
dataset['validation'] = dataset['validation'].select(range(min(500, len(dataset['validation']))))

tokenizer = AutoTokenizer.from_pretrained(cfg['model_name'])
model     = AutoModelForSeq2SeqLM.from_pretrained(cfg['model_name'])

def preprocess(examples):
    inputs  = [cfg['prefix'] + t for t in examples['technical_text']]
    targets = examples['plain_text']
    model_inputs = tokenizer(inputs, max_length=cfg['max_input'],
                             truncation=True, padding=False)
    labels = tokenizer(targets, max_length=cfg['max_target'],
                       truncation=True, padding=False)
    model_inputs['labels'] = labels['input_ids']
    return model_inputs

print("Tokenizing...")
tokenized = dataset.map(preprocess, batched=True,
                        remove_columns=dataset['train'].column_names)

training_args = Seq2SeqTrainingArguments(
    output_dir=f"./{MODEL_KEY}_scilay",
    num_train_epochs=cfg['epochs'],
    per_device_train_batch_size=cfg['batch_size'],
    per_device_eval_batch_size=cfg['batch_size'],
    learning_rate=cfg['learning_rate'],
    warmup_steps=300, weight_decay=0.01,
    eval_strategy="epoch", save_strategy="epoch",
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    predict_with_generate=True, generation_max_length=cfg['max_target'],
    gradient_checkpointing=True, fp16=True,
    logging_steps=100, report_to="none",
    save_total_limit=1,
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, padding=True)

trainer = Seq2SeqTrainer(
    model=model, args=training_args,
    train_dataset=tokenized['train'],
    eval_dataset=tokenized['validation'],
    processing_class=tokenizer, data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

print("Training...")
trainer.train()
print("Done training!")

# ── Generate test predictions ──
N = 50   # match your baseline; bump to 200 later
test_data  = dataset['test'].select(range(min(N, len(dataset['test']))))
sources    = [ex['technical_text'] for ex in test_data]
references = [ex['plain_text']     for ex in test_data]
journals   = [ex.get('journal','') for ex in test_data]

predictions = []
model.eval()
for abstract in sources:
    inputs = tokenizer(cfg['prefix'] + abstract, return_tensors="pt",
                       max_length=cfg['max_input'], truncation=True).to(model.device)
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=cfg['max_target'],
                             num_beams=4, early_stopping=True)
    predictions.append(tokenizer.decode(out[0], skip_special_tokens=True))

pd.DataFrame({'source': sources, 'prediction': predictions,
              'reference': references, 'journal': journals
             }).to_csv(f'{MODEL_KEY}_predictions.csv', index=False)

results = evaluate_system(sources, predictions, references,
                          system_name=f"{MODEL_KEY}_finetuned")
with open(f'{MODEL_KEY}_results.json', 'w') as f:
    json.dump(results, f, indent=2)
print(f"\nSaved {MODEL_KEY}_results.json — now set MODEL_KEY='bart' and re-run.")

import torch
import json
import numpy as np
import pandas as pd
from datasets import load_dataset
from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM,
    Seq2SeqTrainer, Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq, EarlyStoppingCallback
)

# ── Change to "bart" for the second run ──
MODEL_KEY = "bart"

CONFIGS = {
    "bart": {
        "model_name": "bart-base", "max_input": 512, "max_target": 200,
        "learning_rate": 3e-4, "batch_size": 8, "epochs": 3, "prefix": "summarize: ",
    },
    "bart": {
        "model_name": "facebook/bart-base",   # base not large — fits T4
        "max_input": 512, "max_target": 200,
        "learning_rate": 3e-5, "batch_size": 4, "epochs": 3, "prefix": "",
    },
}
cfg = CONFIGS[MODEL_KEY]
print(f"Training: {cfg['model_name']}")

# ── Load SciLay ──
dataset = load_dataset("disi-unibo-nlp/SciLay", "all")
print(f"Train: {len(dataset['train'])} | Val: {len(dataset['validation'])} | Test: {len(dataset['test'])}")

# OPTIONAL: subset training data to save time on T4 (comment out for full run)
dataset['train'] = dataset['train'].select(range(min(5000, len(dataset['train']))))
dataset['validation'] = dataset['validation'].select(range(min(500, len(dataset['validation']))))

tokenizer = AutoTokenizer.from_pretrained(cfg['model_name'])
model     = AutoModelForSeq2SeqLM.from_pretrained(cfg['model_name'])

def preprocess(examples):
    inputs  = [cfg['prefix'] + t for t in examples['technical_text']]
    targets = examples['plain_text']
    model_inputs = tokenizer(inputs, max_length=cfg['max_input'],
                             truncation=True, padding=False)
    labels = tokenizer(targets, max_length=cfg['max_target'],
                       truncation=True, padding=False)
    model_inputs['labels'] = labels['input_ids']
    return model_inputs

print("Tokenizing...")
tokenized = dataset.map(preprocess, batched=True,
                        remove_columns=dataset['train'].column_names)

training_args = Seq2SeqTrainingArguments(
    output_dir=f"./{MODEL_KEY}_scilay",
    num_train_epochs=cfg['epochs'],
    per_device_train_batch_size=cfg['batch_size'],
    per_device_eval_batch_size=cfg['batch_size'],
    learning_rate=cfg['learning_rate'],
    warmup_steps=300, weight_decay=0.01,
    eval_strategy="epoch", save_strategy="epoch",
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    predict_with_generate=True, generation_max_length=cfg['max_target'],
    gradient_checkpointing=True, fp16=True,
    logging_steps=100, report_to="none",
    save_total_limit=1,
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, padding=True)

trainer = Seq2SeqTrainer(
    model=model, args=training_args,
    train_dataset=tokenized['train'],
    eval_dataset=tokenized['validation'],
    processing_class=tokenizer, data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

print("Training...")
trainer.train()
print("Done training!")

# ── Generate test predictions ──
N = 50   # match your baseline; bump to 200 later
test_data  = dataset['test'].select(range(min(N, len(dataset['test']))))
sources    = [ex['technical_text'] for ex in test_data]
references = [ex['plain_text']     for ex in test_data]
journals   = [ex.get('journal','') for ex in test_data]

predictions = []
model.eval()
for abstract in sources:
    inputs = tokenizer(cfg['prefix'] + abstract, return_tensors="pt",
                       max_length=cfg['max_input'], truncation=True).to(model.device)
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=cfg['max_target'],
                             num_beams=4, early_stopping=True)
    predictions.append(tokenizer.decode(out[0], skip_special_tokens=True))

pd.DataFrame({'source': sources, 'prediction': predictions,
              'reference': references, 'journal': journals
             }).to_csv(f'{MODEL_KEY}_predictions.csv', index=False)

results = evaluate_system(sources, predictions, references,
                          system_name=f"{MODEL_KEY}_finetuned")
with open(f'{MODEL_KEY}_results.json', 'w') as f:
    json.dump(results, f, indent=2)
print(f"\nSaved {MODEL_KEY}_results.json — now set MODEL_KEY='bart' and re-run.")

import shutil
for f in ['t5_predictions.csv', 't5_results.json']:
    shutil.copy(f, '/content/results_backup/')
print("T5 results backed up.")

import torch, os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16, bnb_4bit_use_double_quant=True,
)
print("Reloading Llama 3...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, quantization_config=bnb_config, device_map="auto")
model.eval()

def generate(prompt, max_new_tokens=256):
    messages = [{"role": "user", "content": prompt}]
    input_ids = tokenizer.apply_chat_template(
        messages, add_generation_prompt=True,
        return_tensors="pt", return_dict=False).to(model.device)
    with torch.no_grad():
        out = model.generate(input_ids, max_new_tokens=max_new_tokens,
                             do_sample=False, pad_token_id=tokenizer.eos_token_id)
    return tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True).strip()

print("Ready.")

import json
import numpy as np
import pandas as pd
from datasets import load_dataset
from evaluate import load as load_metric

sari_metric = load_metric("sari")

# ── Pool of candidate prompts to search over (per audience) ──
CANDIDATE_PROMPTS = {
    "general": [
        "Rewrite this scientific abstract in plain English for a general reader. Keep all key findings:\n\n{abstract}\n\nPlain version:",
        "Explain the following abstract to someone with no science background, using simple everyday words while keeping the facts accurate:\n\n{abstract}\n\nExplanation:",
        "You are a science journalist. Summarize this abstract for a newspaper's general audience, keeping it accurate but easy to read:\n\n{abstract}\n\nSummary:",
        "Simplify this scientific text so any adult can understand it. Do not add information that is not in the original:\n\n{abstract}\n\nSimplified:",
    ],
    "middle_school": [
        "Rewrite this abstract so a 12-year-old can understand it. Use short sentences and simple words, but keep the facts correct:\n\n{abstract}\n\nSimple version:",
        "You are a science teacher explaining this to a middle school class. Keep it accurate and easy:\n\n{abstract}\n\nExplanation:",
        "Explain this research to a curious middle schooler. Define hard words. Do not make up facts:\n\n{abstract}\n\nExplanation:",
        "Turn this abstract into a simple explanation for a school student aged 12-14, staying faithful to the original findings:\n\n{abstract}\n\nSimple explanation:",
    ],
    "undergraduate": [
        "Rewrite this abstract for an undergraduate who has taken intro science courses. Clarify jargon but keep technical accuracy:\n\n{abstract}\n\nClarified version:",
        "Explain this abstract to a first-year college student, keeping the important technical points but making it clearer:\n\n{abstract}\n\nExplanation:",
        "You are a teaching assistant. Rewrite this for undergraduates, preserving accuracy while improving readability:\n\n{abstract}\n\nRewrite:",
        "Make this abstract accessible to an undergraduate science student without oversimplifying the findings:\n\n{abstract}\n\nAccessible version:",
    ],
}

# ── Load data ──
dataset = load_dataset("disi-unibo-nlp/SciLay", "all")
val_data  = dataset['validation'].select(range(15))   # small val set for search
test_data = dataset['test'].select(range(50))         # same 50 as baseline

val_src  = [ex['technical_text'] for ex in val_data]
val_ref  = [ex['plain_text']     for ex in val_data]
test_src = [ex['technical_text'] for ex in test_data]
test_ref = [ex['plain_text']     for ex in test_data]
test_jrn = [ex.get('journal','') for ex in test_data]

# ── Search: find best prompt per audience on validation set ──
best_prompts = {}
for audience, candidates in CANDIDATE_PROMPTS.items():
    print(f"\n=== Searching prompts for: {audience} ===")
    best_sari, best_p = -1, None
    for idx, template in enumerate(candidates):
        preds = [generate(template.format(abstract=a)) for a in val_src]
        sari = sari_metric.compute(sources=val_src, predictions=preds,
                                   references=[[r] for r in val_ref])['sari']
        print(f"  candidate {idx+1}: SARI={sari:.2f}")
        if sari > best_sari:
            best_sari, best_p = sari, template
    best_prompts[audience] = best_p
    print(f"  BEST for {audience}: SARI={best_sari:.2f}")

# Save which prompts won
with open('best_prompts.json', 'w') as f:
    json.dump(best_prompts, f, indent=2)

# ── Evaluate best prompts on the test set ──
all_results = {}
for audience, template in best_prompts.items():
    print(f"\n=== Testing optimized prompt: {audience} ===")
    preds = []
    for i, a in enumerate(test_src):
        if i % 10 == 0: print(f"  {i}/{len(test_src)}")
        preds.append(generate(template.format(abstract=a)))

    pd.DataFrame({'source': test_src, 'prediction': preds,
                  'reference': test_ref, 'journal': test_jrn
                 }).to_csv(f'promptsearch_{audience}_predictions.csv', index=False)

    results = evaluate_system(test_src, preds, test_ref,
                              system_name=f"promptsearch_{audience}")
    all_results[audience] = results

with open('promptsearch_results.json', 'w') as f:
    json.dump(all_results, f, indent=2)
print("\nDone! Saved promptsearch_results.json + best_prompts.json")

import json, os, shutil
os.makedirs('/content/results_backup', exist_ok=True)
for f in os.listdir('.'):
    if 'promptsearch' in f or 'best_prompts' in f:
        shutil.copy(f, '/content/results_backup/')
print("Backed up:", [f for f in os.listdir('/content/results_backup') if 'prompt' in f])

import json, numpy as np, pandas as pd
from datasets import load_dataset

# ── Prompts ──
INIT_PROMPT = (
    "You are a science communicator. Rewrite the following scientific abstract "
    "in plain English for a general reader with no science background. "
    "Keep all key findings but use simple language.\n\n"
    "Abstract:\n{abstract}\n\nSimplified version:"
)
CRITIQUE_PROMPT = (
    "You are a fact-checker reviewing a simplified scientific abstract.\n\n"
    "ORIGINAL:\n{abstract}\n\n"
    "SIMPLIFIED:\n{simp}\n\n"
    "Check: (1) any scientific claims DROPPED? (2) any claims CHANGED/inaccurate? "
    "(3) anything ADDED not in the original?\n"
    "If there are problems, write a REVISED simplified version that fixes them "
    "while staying simple. If it is already accurate, reply exactly: NO CHANGES NEEDED\n\n"
    "Response:"
)

# ── NLI-based FactScore helper (reuse the model from Step 3) ──
def fact_score_single(source, pred):
    inputs = nli_tok(source, pred, truncation=True, max_length=512, return_tensors="pt")
    if torch.cuda.is_available():
        inputs = {k: v.cuda() for k, v in inputs.items()}
    with torch.no_grad():
        probs = torch.softmax(nli_model(**inputs).logits, dim=-1)[0]
    return float(probs[0].item())   # entailment probability

# ── Self-refinement loop ──
def self_refine(abstract, max_iters=3, min_gain=0.01):
    current = generate(INIT_PROMPT.format(abstract=abstract))
    cur_score = fact_score_single(abstract, current)
    history = [cur_score]

    for _ in range(max_iters):
        resp = generate(CRITIQUE_PROMPT.format(abstract=abstract, simp=current))
        if "NO CHANGES NEEDED" in resp.upper():
            break
        new_score = fact_score_single(abstract, resp)
        history.append(new_score)
        if new_score <= cur_score + min_gain:
            break
        current, cur_score = resp, new_score
    return current, history

# ── Run on the same 50 test examples ──
dataset   = load_dataset("disi-unibo-nlp/SciLay", "all")
test_data = dataset['test'].select(range(50))
sources   = [ex['technical_text'] for ex in test_data]
references= [ex['plain_text']     for ex in test_data]
journals  = [ex.get('journal','') for ex in test_data]

predictions = []
iter_scores = {0: [], 1: [], 2: [], 3: []}

for i, abstract in enumerate(sources):
    if i % 10 == 0:
        print(f"{i}/50")
    pred, hist = self_refine(abstract)
    predictions.append(pred)
    for it, sc in enumerate(hist):
        if it in iter_scores:
            iter_scores[it].append(sc)

pd.DataFrame({'source': sources, 'prediction': predictions,
              'reference': references, 'journal': journals
             }).to_csv('self_refine_predictions.csv', index=False)

results = evaluate_system(sources, predictions, references, "llama3_self_refine")
results['iter_factscore'] = {str(k): round(float(np.mean(v)), 4)
                             for k, v in iter_scores.items() if v}
print("\nPer-iteration FactScore:", results['iter_factscore'])

with open('self_refine_results.json', 'w') as f:
    json.dump(results, f, indent=2)
print("Saved self_refine_results.json")

from google.colab import drive
drive.mount('/content/drive')

import shutil
for f in ['self_refine_predictions.csv', 'self_refine_results.json']:
    shutil.copy(f, '/content/results_backup/')
print("Self-refine results backed up.")

import json, numpy as np, pandas as pd

# Files saved across steps 4-7
PREDICTION_FILES = {
    "T5 (fine-tuned)":        "t5_predictions.csv",
    "BART (fine-tuned)":      "bart_predictions.csv",
    "Llama3 (zero-shot)":     "llama3_zeroshot_general_predictions.csv",
    "Llama3 + Prompt Opt.":   "promptsearch_general_predictions.csv",
    "Llama3 + Self-Refine":   "self_refine_predictions.csv",
}

# Journal → domain
def journal_to_domain(j):
    j = str(j).lower()
    if any(x in j for x in ['cancer','pathogen','neglected','mbio']): return 'medicine'
    if any(x in j for x in ['computational','scientific data']):       return 'cs'
    if any(x in j for x in ['genetics','biology','nature','animal','insect','plos']): return 'biology'
    return 'other'

# ── Final results table ──
print("=== FINAL RESULTS TABLE ===")
rows = []
for name, path in PREDICTION_FILES.items():
    try:
        df = pd.read_csv(path)
        r = evaluate_system(df['source'].tolist(), df['prediction'].tolist(),
                            df['reference'].tolist(), system_name=name)
        rows.append(r)
    except FileNotFoundError:
        print(f"  missing: {path}")

results_df = pd.DataFrame(rows)
print(results_df[['system','SARI','BERTScore','ROUGE-L','FKGL_delta','FactScore']].to_string(index=False))
results_df.to_csv('final_results_table.csv', index=False)

# ── Audience breakdown (prompt-opt outputs) ──
print("\n=== AUDIENCE BREAKDOWN ===")
aud_rows = {}
for aud in ['middle_school','general','undergraduate']:
    path = f'promptsearch_{aud}_predictions.csv'
    try:
        df = pd.read_csv(path)
        r = evaluate_system(df['source'].tolist(), df['prediction'].tolist(),
                            df['reference'].tolist(), system_name=f"promptopt_{aud}")
        aud_rows[aud] = r
        print(f"  {aud}: SARI={r['SARI']} FKGL_delta={r['FKGL_delta']} FactScore={r['FactScore']}")
    except FileNotFoundError:
        print(f"  missing: {path}")
json.dump(aud_rows, open('audience_breakdown_results.json','w'), indent=2)

# ── Domain breakdown (on the general prompt-opt output) ──
print("\n=== DOMAIN BREAKDOWN ===")
dom_rows = {}
try:
    df = pd.read_csv('promptsearch_general_predictions.csv')
    df['domain'] = df['journal'].apply(journal_to_domain)
    for dom in ['medicine','biology','cs']:
        sub = df[df['domain']==dom]
        if len(sub) >= 5:
            r = evaluate_system(sub['source'].tolist(), sub['prediction'].tolist(),
                                sub['reference'].tolist(), system_name=f"domain_{dom}")
            dom_rows[dom] = r
            print(f"  {dom} (n={len(sub)}): SARI={r['SARI']} FactScore={r['FactScore']}")
        else:
            print(f"  {dom}: only {len(sub)} examples, skipping")
except FileNotFoundError:
    print("  missing general predictions")
json.dump(dom_rows, open('domain_breakdown_results.json','w'), indent=2)

print("\nSaved final_results_table.csv, audience_breakdown_results.json, domain_breakdown_results.json")

import shutil
for f in ['final_results_table.csv','audience_breakdown_results.json','domain_breakdown_results.json']:
    shutil.copy(f, '/content/results_backup/')
print("backed up")

from google.colab import files

# Download all your figures and results
for f in ['figure1_systems.pdf', 'figure1_systems.png',
          'figure2_tradeoff.pdf', 'figure2_tradeoff.png',
          'figure3_selfrefine.pdf', 'figure3_selfrefine.png',
          'final_results_table.csv',
          'audience_breakdown_results.json',
          'self_refine_results.json']:
    try:
        files.download(f)
    except Exception as e:
        print(f"skip {f}: {e}")

from google.colab import drive
drive.mount('/content/drive')

import shutil, os
os.makedirs('/content/drive/MyDrive/NLP_project', exist_ok=True)

for f in os.listdir('/content'):
    if f.endswith(('.pdf','.png','.csv','.json')):
        shutil.copy(f'/content/{f}', '/content/drive/MyDrive/NLP_project/')
print("Saved to Google Drive → NLP_project folder")